export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"

export const REQUEST_PEOPLE_PENDING = "REQUEST_PEOPLE_PENDING"
export const REQUEST_PEOPLE_SUCCESS = "REQUEST_PEOPLE_SUCCESS"
export const REQUEST_PEOPLE_FAILED = "REQUEST_PEOPLE_FAILED"

export const REQUEST_PLANETS_PENDING = "REQUEST_PLANETS_PENDING"
export const REQUEST_PLANETS_SUCCESS = "REQUEST_PLANETS_SUCCESS"
export const REQUEST_PLANETS_FAILED = "REQUEST_PLANETS_FAILED"

export const REQUEST_STARSHIPS_PENDING = "REQUEST_STARSHIPS_PENDING"
export const REQUEST_STARSHIPS_SUCCESS = "REQUEST_STARSHIPS_SUCCESS"
export const REQUEST_STARSHIPS_FAILED = "REQUEST_STARSHIPS_FAILED"

export const TOGGLE_HIDDEN = "TOGGLE_HIDDEN"